baseURL = "https://wayism.github.io"
languageCode = "en-us"
title = "Wayism - The Butterfly Path"
publishDir = "docs"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  description = "Existential philosophy where souls evolve into immortal spirits"
  schemaType = "EducationalOrganization"
  aiCrawlable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[languages]
  [languages.en]
    weight = 1
  [languages.zh]
    weight = 2
  [languages.es]
    weight = 3

[permalinks]
ontology = "/ontology/:slug/"
faq = "/faq/:slug/"

[related]
  threshold = 80
  includeNewer = true
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "concepts"
    weight = 200
