# NEW FROM CLAUDE Simple workflow for building Hugo and committing to /docs
name: Build Hugo site

on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'
          extended: true
      
      - name: Build
        run: hugo --minify --baseURL "https://wayism.github.io/org/" -d docs
      
      - name: Commit docs folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "Build site [skip ci]"
          git push
